### ISSUE TITLE
[FEATURE] Publish workflow schema

### ISSUE THREAD

**Issue by joscha** [PipedreamHQ/pipedream#12464]
**Is your feature request related to a problem? Please describe.**

I am trying to unit test my workflows. For that I'd like to process the yaml file of a workflow and run the steps in a workflow as defined in the workflow file. Unfortunately I can't find any information on the schema (for example `workflow.state/2022.04`) like in here:

```yaml
# DO NOT EDIT THIS FILE
---
schema: workflow.state/2022.04
id: p_NMCGQlD
```

to be sure what shape the yaml can have.

**Describe the solution you'd like**

Publish the workflow schema definitions publicly.

**Do you have a workaround?**

Reverse engineering the generated workflow file and deriving the schema.
