### ISSUE TITLE
[FEATURE] Copy/paste Steps between Workflows

### ISSUE THREAD

**Issue by dzg** [PipedreamHQ/pipedream#2209]
Is there no way to copy a Step from one Workflow and paste in another?
Would be super handy.

**Comment by dylburger** [comment]
@dzg If you had a way to view the entire code behind the workflow, for example:

```yaml
steps:
  step1:
    type: action
    name: google_sheets_add_new_row
    params:
      ...
```

Would that solve your use case? We're working on a way to do that right now ([tracking here](https://github.com/PipedreamHQ/pipedream/issues/220)). In that model, you'd be able to view the entire workflow configuration as code — in the Pipedream UI, in your Git repo, etc. — and you'd be able to copy and paste code from one workflow to another, copying the whole step and its configuration / code.
